### PR TITLE
Types

### PR DESCRIPTION
**Pull request by FFKL**
Hello! I've added types, but it broke backward compatibility for imports. Review please this version. I thinking about saving current imports with entry point, but now I have problems with it :smile:

### CODE REVIEW

**Comment by bahung1221** [comment]
Cool, thanks bro 😄 ,

I think the CacheAll.Cacher should be an `interface` instead `class`, because we just call `cache.get()` without `new Cache(...)`.

I also think we should have three `d.ts` files for three entry points (memory.js, file.js, redis.js) instead one entry point, is it possible to have an config.ts (or something) that export `CacheAll` namespace, and then it will be import into three `d.ts` entry point?

Currently, i separate entry points to create independent singleton cache instance, i will research to find more ways to archive it.

**Comment by FFKL** [comment]
Ok. I'll try create separate files :smile: Doesn't import from index.js file create singleton?

**Comment by bahung1221** [comment]
> Ok. I'll try create separate files 😄 Doesn't import from index.js file create singleton?

No, it does.
But we must create three instance regardless the users just want to use one. Currently, in each entry point i exported an `returned instance from an function`, and each entry point will be call only when user require it, if they require just one entry (redis for example), only one cache instance will be create.

```js
module.exports = require('./src/cache')('file')
```

If we use index.js file, we must do something like below:
```js
// Maybe user just want to use one, but three instance was created
module.exports.file = require('./src/cache')('file')
module.exports.memory = require('./src/cache')('memory')
module.exports.redis = require('./src/cache')('redis')
```

Ofcourse, the effect is too small 😄

**Comment by FFKL** [comment]
Hello! I've reworked types. Now it works with 4 d.ts files, but they are identical :smile: Check please. Have you some suggestions?

**Comment by bahung1221** [comment]
Hi bro, i think it fine, i just split `config.d.ts` and i have no idea about identical functions.
Please help me review my commit, i tested and it worked, but is it has any problem? 😄

**Comment by FFKL** [comment]
@bahung1221 I think, i found right way for types :smile: Check please. Same functions for all modules

**Comment by bahung1221** [comment]
Cool! i have some problems when try to test it using relative path, lol. so i will release an beta version of it and then try to make it run in example project, it will be `2.1.0-beta.0`

Thank bro 😄

**Comment by bahung1221** [comment]
#2

**Pull request merged**
