### PR TITLE
Empty prefix usage

### PR DESCRIPTION
**Pull request by FFKL**
I've add possibility to use empty prefix (empty string in options)

### CODE REVIEW

**Comment by bahung1221** [comment]
Thank you very much @FFKL, 
I will write some unit test for it now and then i will publish new version to npm tonight 👍

**Comment by FFKL** [comment]
@bahung1221 I think, I'll add some type defs later :smile:

**Comment by bahung1221** [comment]
It sound great! 
I thought about typescript or coffeescript ([#2](https://github.com/bahung1221/cache-all/issues/2)) but it was delayed because i think this library has too little user, lol 😃

I'd appreciate PR, and i will go with you
Thanks

**Comment by bahung1221** [comment]
By the way, your PR was published to npm as version [v2.0.6](https://www.npmjs.com/package/cache-all) 👍

**Comment by FFKL** [comment]
@bahung1221 cool!

**Pull request merged**
